### ISSUE TITLE
[BUG]经测试fac0.2.10rc16版本AntdTable的data参数中存在None时会报错，回退至0.2.9则正常

### ISSUE THREAD

**Issue by insistence** [CNFeffery/feffery-antd-components#99]
详细报错信息为：Uncaught TypeError: Cannot read properties of null (reading '$$typeof')
    at async-antd_table.v0_2_10-rc16m1695099254.js:1:57575
    at feffery_antd_components.v0_2_10-rc16m1695200571.min.js:1:50743
    at feffery_antd_components.v0_2_10-rc16m1695200571.min.js:1:54947
    at Te (feffery_antd_components.v0_2_10-rc16m1695200571.min.js:1:31287)
    at Kr (feffery_antd_components.v0_2_10-rc16m1695200571.min.js:1:54919)
    at m.omitBy (feffery_antd_components.v0_2_10-rc16m1695200571.min.js:1:60401)
    at async-antd_table.v0_2_10-rc16m1695099254.js:1:57551
    at Array.map (<anonymous>)
    at onChange (async-antd_table.v0_2_10-rc16m1695099254.js:1:57477)
    at async-antd_table.v0_2_10-rc16m1695099254.js:1:1022784

**Comment by CNFeffery** [comment]
`0.2.10rc17`已修复
